### PR TITLE
Add new library

### PR DESCRIPTION
**Pull request by CodeGuy92**
Add a new library design.

Not too different, tough. Just some minor transitions & re-arrangements.
https://user-images.githubusercontent.com/79767244/129445402-957697b2-a379-414d-aa9f-efa55db20823.png
https://user-images.githubusercontent.com/79767244/129445418-bc0018ab-2bce-450b-bf84-932fab5f519d.png

Please download the [library-pr](https://github.com/CodeGuy92/Customized/tree/library-pr) branch for beta testing.

### CODE REVIEW

**Comment by CodeGuy92** [comment]
@CST1229 You are summoned

**Comment by CST1229** [comment]
Why not make them even more horizontal? Otherwise, this happens on smaller screens:
pic

**Comment by CodeGuy92** [comment]
Actually can you add some shadow to the text (not including buttons)
text-shadow: 2px 2px COLOR;

**Comment by CodeGuy92** [comment]
frick i commited the theme on the wrong branch

**Comment by CodeGuy92** [comment]
Screen compatibillity test:
https://user-images.githubusercontent.com/79767244/129451807-6745c4d5-809f-4f16-bdaa-6768a404259d.png
https://user-images.githubusercontent.com/79767244/129451818-fee4bdfc-33cf-4798-a824-f55459cab861.png
https://user-images.githubusercontent.com/79767244/129451826-dde0f861-b0d6-4c18-be85-0792d5480ca7.png
https://user-images.githubusercontent.com/79767244/129451841-6dad1c95-5774-4efb-aa18-70a73ca46e47.png

**Pull request merged**
