### PR TITLE
Use object for costume library

### LINKED ISSUE #12: more efficient way for library
Currently, we are using an else-if. It would be better if we used a more efficient solution.

### PR DESCRIPTION
**Pull request by CST1229**
Resolves #12

### CODE REVIEW

**Comment by CodeGuy92** [comment]
hmph

**Comment by CodeGuy92** [comment]
Could you please create a different script (lib.js) for this?

**Comment by CST1229** [comment]
I could.

**Comment by CodeGuy92** [comment]
Don't forget to check this for every pull you do
image

**Comment by CST1229** [comment]
> 
> 
> Don't forget to check this for every pull you do
> image

I do have it enabled
kép

**Comment by CodeGuy92** [comment]
> > Don't forget to check this for every pull you do
> > image
> 
> I do have it enabled
> kép

Ok then, just please create a different script (lib.js) & i'll merge the pull

**Comment by CST1229** [comment]
> 
> 
> > > Don't forget to check this for every pull you do
> > > image
> > 
> > 
> > I do have it enabled
> > kép
> 
> Ok then, just please create a different script (lib.js) & i'll merge the pull

I did that a long while ago but forgot to push the changes... oops

**Pull request merged**
